### ISSUE TITLE
passing active theme name with next-themes doesn't change giscus theme upon refresh

### ISSUE THREAD

**Issue by dannysteenman** [giscus/giscus-component#190]
On the latest `@giscus/react: 2.0.3` passing the active theme name from `next-themes 0.1.1` doesn't change the giscus theme upon refresh. For example when dark mode is toggled the giscus theme becomes dark as expected, but when you refresh the browser or reload the giscus iframe then the giscus theme turns back to light on a dark themed page.

```ts
import Giscus, { Theme } from '@giscus/react';
import { useTheme } from 'next-themes';

type GiscusCommentProps = {
  category: string;
  categoryId: string;
};

export default function GiscusComment({ category, categoryId }: GiscusCommentProps) {
  const { theme } = useTheme();

  return (
    <Giscus
      repo='<repoName>'
      repoId='<repoId>'
      category={category}
      categoryId={categoryId}
      mapping='pathname'
      reactionsEnabled='0'
      emitMetadata='0'
      theme={theme as Theme}
    />
  );
}
```

In version 1.1.2 of `@giscus/react` it worked correctly, as an example:

```ts
import { Giscus, Theme } from '@giscus/react';
import { useTheme } from 'next-themes';

type GiscusCommentProps = {
  category: string;
  categoryId: string;
};

export default function GiscusComment({ category, categoryId }: GiscusCommentProps) {
  const { theme } = useTheme();

  return (
    <Giscus
      repo='<repoName>'
      repoId='<repoId>'
      category={category}
      categoryId={categoryId}
      mapping='pathname'
      reactionsEnabled='0'
      emitMetadata='0'
      theme={theme as Theme}
    />
  );
}
```

**Comment by laymonage** [comment]
Fix released in 2.0.4. Thanks for the report!

**Comment by markshenouda** [comment]
This issue still exists in the latest version

![Screen Shot 2022-08-22 at 12 23 02 PM](https://user-images.githubusercontent.com/49324987/185900165-bc7a7ee7-2a47-4ef5-a8de-ece379298e21.png)

**Comment by laymonage** [comment]
@markshenouda The issue is not with giscus, it's with how you use next-themes with it.

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/6379424/185900850-a9ab7280-dd57-4a01-a1a5-b8bf57bf3fe0.png">


The `theme` property returned by `useTheme()` in your use case returns `system`, which is not a valid giscus theme. Please use the `resolvedTheme` value returned by `useTheme()` instead.

Example: https://github.com/laymonage/base/blob/main/src/components/Giscus.tsx

**Comment by markshenouda** [comment]
Thank you so much for explaining that, I just spend too much time debugging this bug
